# Generated by Django 4.2.13 on 2024-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=500, null=True)),
                ('description2', models.CharField(blank=True, max_length=500, null=True)),
                ('image_title', models.CharField(max_length=255)),
                ('image_class', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_title', models.CharField(max_length=255)),
                ('image_class', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='food_gallery')),
            ],
            options={
                'verbose_name': 'Food Gallery',
                'verbose_name_plural': 'Food Gallery',
            },
        ),
        migrations.CreateModel(
            name='FoodGalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Food Gallery Main',
                'verbose_name_plural': 'Food Gallery Main',
            },
        ),
        migrations.CreateModel(
            name='Post2List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Post2 List',
                'verbose_name_plural': 'Post2 List',
            },
        ),
        migrations.CreateModel(
            name='ResentPost1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=500, null=True)),
                ('description2', models.CharField(blank=True, max_length=500, null=True)),
                ('description3', models.CharField(blank=True, max_length=1500, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_class', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resent_post1')),
                ('llink_url1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Resent Post1',
                'verbose_name_plural': 'Resent Post1',
            },
        ),
        migrations.CreateModel(
            name='ResentPost2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=500, null=True)),
                ('description2', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Resent Post2',
                'verbose_name_plural': 'Resent Post2',
            },
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider_images')),
            ],
            options={
                'verbose_name': 'Slider Images',
                'verbose_name_plural': 'Slider Images',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Sliders',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonials Main',
                'verbose_name_plural': 'Testimonials Main',
            },
        ),
        migrations.CreateModel(
            name='WebDesine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=500, null=True)),
                ('description2', models.CharField(blank=True, max_length=500, null=True)),
                ('description3', models.CharField(blank=True, max_length=500, null=True)),
                ('description4', models.CharField(blank=True, max_length=2500, null=True)),
                ('description5', models.CharField(blank=True, max_length=2500, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_class', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='web_desine')),
                ('link_url1', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url2', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url4', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url5', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url6', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name4', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name5', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name6', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Web Desine',
                'verbose_name_plural': 'Web Desine',
            },
        ),
    ]
