# Generated by Django 4.2.13 on 2024-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_llink_url1_resentpost1_link_url1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebDesine',
            new_name='WebDesign',
        ),
    ]
