# Generated by Django 4.2.13 on 2024-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery_gallery1_gallerymain_alter_webdesign_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery1',
            name='link_name3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery1',
            name='link_url3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='link_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery1',
            name='link_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery1',
            name='link_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery1',
            name='link_url1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery1',
            name='link_url2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
