# Generated by Django 4.2.13 on 2024-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gallery1_link_name3_gallery1_link_url3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1500)),
                ('image_title', models.CharField(max_length=255)),
                ('image_class', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog1')),
                ('text', models.CharField(max_length=255)),
                ('link_url1', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url2', models.URLField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Blog1',
                'verbose_name_plural': 'Blog1',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=2500, null=True)),
                ('description2', models.CharField(blank=True, max_length=2500, null=True)),
                ('description3', models.CharField(blank=True, max_length=2500, null=True)),
                ('description4', models.CharField(blank=True, max_length=2500, null=True)),
                ('description5', models.CharField(blank=True, max_length=2500, null=True)),
                ('description6', models.CharField(blank=True, max_length=2500, null=True)),
                ('description7', models.CharField(blank=True, max_length=2500, null=True)),
                ('image_title', models.CharField(max_length=255)),
                ('image_class', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_post')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url1', models.URLField(blank=True, max_length=255, null=True)),
                ('link_url2', models.URLField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url4', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url5', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name4', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='Blogs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1500)),
                ('image_title', models.CharField(max_length=255)),
                ('image_class', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blogs2')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blogs2',
                'verbose_name_plural': 'Blogs2',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=255)),
                ('image_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='comments')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Comments Main',
                'verbose_name_plural': 'Comments Main',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=250)),
                ('description1', models.CharField(blank=True, max_length=250, null=True)),
                ('description2', models.CharField(blank=True, max_length=250, null=True)),
                ('description3', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_namber', models.CharField(max_length=255)),
                ('email_text', models.CharField(max_length=255)),
                ('email_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='PopularPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('link_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Popular Posts',
                'verbose_name_plural': 'Popular Posts',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SideBarMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Side Bar Main',
                'verbose_name_plural': 'Side Bar Main',
            },
        ),
    ]
