# Generated by Django 4.2.13 on 2024-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog1_blogpost_blogs2_comments_commentsmain_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='link_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='link_url1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='link_url2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
