# Generated by Django 4.2.13 on 2024-11-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_link_name1_contact_link_name2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='phone_namber',
            new_name='phone_number',
        ),
    ]
