# Generated by Django 4.2.13 on 2024-11-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_phone_namber_location_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularposts',
            old_name='title',
            new_name='link_name',
        ),
    ]
